project_id = "yxdpqubitozndqgaacbm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-newsletter]
verify_jwt = false

[functions.newsletter-scheduler]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false